# -*- coding: utf-8 -*-
"""MRP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKoGlfPFb6rEdYzQNb_AEd6xnsqBloki
"""

# movie_revenue_app.py

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

st.set_page_config(page_title="Movie Revenue Predictor")
st.title("🎬 Movie Revenue Predictor")
st.markdown("Upload movie data, perform EDA, and predict revenue using ML models.")

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv("boxoffice.csv")
    df.columns = [col.lower().strip() for col in df.columns]
    return df

df = load_data()

# Sidebar info
st.sidebar.header("📋 Column Info")
st.sidebar.write(df.columns.tolist())

# Numeric columns for selection
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
if 'world_revenue' in numeric_cols:
    numeric_cols.remove('world_revenue')

# Data preview
st.subheader("🔍 Dataset Preview")
st.dataframe(df.head())

# Statistics summary
st.subheader("📊 Summary Statistics")
st.write(df.describe(include='all'))

# Revenue distribution
st.subheader("💰 Revenue Distribution")
fig1, ax1 = plt.subplots()
sns.histplot(df['world_revenue'], bins=30, kde=True, ax=ax1)
st.pyplot(fig1)

# Feature selection
st.subheader("🧮 Feature Selection")
selected_features = st.multiselect("Choose features for prediction:", numeric_cols, default=['budget', 'opening_revenue'])

# Model selection
model_type = st.radio("📌 Select Model", ["Linear Regression", "Random Forest"])

if selected_features:
    df = df.dropna(subset=['world_revenue'])

    X = df[selected_features]
    y = df['world_revenue']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    numeric_transformer = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ])

    preprocessor = ColumnTransformer([
        ('num', numeric_transformer, selected_features)
    ])

    if model_type == "Linear Regression":
        model = Pipeline([
            ('preprocessor', preprocessor),
            ('regressor', LinearRegression())
        ])
    else:
        model = Pipeline([
            ('preprocessor', preprocessor),
            ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))
        ])

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    st.subheader("📈 Model Evaluation")
    st.write(f"**R² Score:** {r2_score(y_test, y_pred):.4f}")
    st.write(f"**MSE:** {mean_squared_error(y_test, y_pred):,.2f}")
    st.write(f"**MAE:** {mean_absolute_error(y_test, y_pred):,.2f}")
    st.write(f"**RMSE:** {np.sqrt(mean_squared_error(y_test, y_pred)):.2f}")

    st.subheader("📉 Actual vs Predicted Revenue")
    fig2, ax2 = plt.subplots()
    sns.scatterplot(x=y_test, y=y_pred, ax=ax2)
    ax2.set_xlabel("Actual Revenue")
    ax2.set_ylabel("Predicted Revenue")
    ax2.set_title("Actual vs Predicted")
    st.pyplot(fig2)
else:
    st.warning("Select at least one feature to proceed.")